import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import useStore from "../zustand/store";

function Home() {
  const { user, setUser } = useStore()
  const [query, setQuery] = useState("");
  const [response, setResponse] = useState("");
  const navigate = useNavigate()

  //   <Link to='/login'></Link>

  const askAI = () => {

    if (query === "") {
      alert("Please enter your question");
      return;
    }

    setResponse(`AI Response:

You asked: "${query}"

This is a demo AI response.
In the real Vibe Coding platform
this would be generated by AI.
`);
  };


  useEffect(() => {
    const storedUser = localStorage.getItem("user");
    if (storedUser) {
      const userData = JSON.parse(storedUser);
      setUser(userData);
    }
  }, [])

  return (

    <div className="font-sans min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-indigo-100">

      {/* NAVBAR */}
      <nav className="flex justify-between items-center px-12 py-5 bg-white/80 backdrop-blur-md shadow">

        <div className="flex items-center gap-3">

          <div className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white w-10 h-10 flex items-center justify-center rounded-xl font-bold">
            VC
          </div>

          <h1 className="text-xl font-semibold">
            Vibe Coding
          </h1>

        </div>

        <div className="flex gap-8 text-gray-600">

          <a href="#">Home</a>
          <a href="#">Features</a>
          <a href="#">How It Works</a>
          <a href="#contact">Contact</a>

        </div>

        <div className="flex gap-4">
{
  user ? (
    <button
      onClick={() => navigate('/dashboard')}
      className="px-5 py-2 rounded-full bg-gray-200"
    >
      {user.email}
    </button>
  ) : (
    <button
      onClick={() => navigate('/login')}
      className="px-5 py-2 rounded-full bg-gray-200"
    >
      Login
    </button>
  )
}

          <button onClick={() => { navigate('/dashboard') }} className="px-6 py-2 rounded-full text-white bg-gradient-to-r from-blue-500 to-indigo-600">
            Try AI
          </button>

        </div>

      </nav>


      {/* HERO SECTION */}
      <section className="relative py-32 px-10 overflow-hidden">

        <div className="absolute inset-0 bg-gradient-to-r from-blue-200 via-purple-200 to-indigo-200 blur-3xl opacity-60"></div>

        <div className="relative max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center">

          <div>

            <h1 className="text-6xl font-bold text-gray-900 leading-tight mb-6">

              Ask Anything
              <span className="text-blue-600"> With AI</span>

            </h1>

            <p className="text-lg text-gray-600 mb-8">

              Vibe Coding is your intelligent AI assistant.
              Ask any question and instantly get smart answers.

            </p>

            <div className="flex gap-3">

              <input
                type="text"
                placeholder="Example: What is artificial intelligence?"
                className="px-5 py-3 rounded-lg w-96 border shadow"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />

              <button
                onClick={askAI}
                className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Ask AI
              </button>

            </div>

            <div className="flex gap-6 mt-6 text-sm text-gray-500">

              <span>⚡ Instant Answers</span>
              <span>🤖 AI Powered</span>
              <span>🌍 Ask Anything</span>

            </div>

          </div>


          {/* RESPONSE WINDOW */}
          <div className="bg-gray-900 text-green-400 rounded-xl shadow-2xl p-6">

            <div className="flex gap-2 mb-4">

              <div className="w-3 h-3 bg-red-500 rounded-full"></div>
              <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
              <div className="w-3 h-3 bg-green-500 rounded-full"></div>

            </div>

            <pre className="text-sm whitespace-pre-wrap">

              {response || `AI response will appear here.

Example question:
"What is machine learning?"`}

            </pre>

          </div>

        </div>

      </section>


      {/* FEATURES */}
      <section className="py-24 px-10">

        <h2 className="text-4xl font-bold text-center mb-16">
          Powerful Features
        </h2>

        <div className="grid md:grid-cols-3 gap-10 max-w-6xl mx-auto">

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl">
            <h3 className="text-xl font-semibold mb-3">🤖 AI Assistant</h3>
            <p className="text-gray-600">Get intelligent answers instantly.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl">
            <h3 className="text-xl font-semibold mb-3">⚡ Fast Results</h3>
            <p className="text-gray-600">AI responses delivered in seconds.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl">
            <h3 className="text-xl font-semibold mb-3">📚 Knowledge Engine</h3>
            <p className="text-gray-600">Explore knowledge across many topics.</p>
          </div>

        </div>

      </section>


      {/* HOW IT WORKS */}
      <section className="py-24 bg-white">

        <h2 className="text-4xl font-bold text-center mb-16">
          How Vibe Coding Works
        </h2>

        <div className="grid md:grid-cols-3 gap-12 max-w-6xl mx-auto px-10">

          <div className="p-8 rounded-xl shadow-lg bg-gradient-to-br from-blue-50 to-blue-100">
            <h3 className="text-xl font-bold mb-3">1️⃣ Ask a Question</h3>
            <p className="text-gray-600">Enter any query into the AI input.</p>
          </div>

          <div className="p-8 rounded-xl shadow-lg bg-gradient-to-br from-purple-50 to-purple-100">
            <h3 className="text-xl font-bold mb-3">2️⃣ AI Understands</h3>
            <p className="text-gray-600">AI analyzes your question.</p>
          </div>

          <div className="p-8 rounded-xl shadow-lg bg-gradient-to-br from-indigo-50 to-indigo-100">
            <h3 className="text-xl font-bold mb-3">3️⃣ Get Answers</h3>
            <p className="text-gray-600">Receive intelligent responses instantly.</p>
          </div>

        </div>

      </section>


      {/* PROFESSIONAL CONTACT SECTION */}
      <section id="contact" className="py-24">

        <h2 className="text-4xl font-bold text-center mb-16">
          Contact Us
        </h2>

        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 px-10">

          {/* CONTACT INFO */}
          <div className="space-y-6">

            <div className="bg-white p-6 rounded-xl shadow">
              <h3 className="font-semibold text-lg mb-2">📧 Email</h3>
              <p className="text-gray-600">support@vibecoding.com</p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow">
              <h3 className="font-semibold text-lg mb-2">📍 Location</h3>
              <p className="text-gray-600">India</p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow">
              <h3 className="font-semibold text-lg mb-2">💬 Support</h3>
              <p className="text-gray-600">24/7 AI powered support</p>
            </div>

          </div>


          {/* CONTACT FORM */}
          <div className="bg-white p-8 rounded-xl shadow-lg">

            <input
              type="text"
              placeholder="Your Name"
              className="w-full p-3 border rounded-lg mb-4"
            />

            <input
              type="email"
              placeholder="Your Email"
              className="w-full p-3 border rounded-lg mb-4"
            />

            <textarea
              placeholder="Your Message"
              className="w-full p-3 border rounded-lg mb-4"
              rows="4"
            />

            <button className="w-full py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
              Send Message
            </button>

          </div>

        </div>

      </section>


      {/* FOOTER */}
      <footer className="bg-gray-900 text-gray-400 py-12 text-center">

        <p>© 2026 Vibe Coding</p>

      </footer>

    </div>
  );
}

export default Home;